# Generated by Django 4.2.4 on 2023-12-12 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actividades', '0003_friendship_created_friendship_creator_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
