# Generated by Django 4.2.4 on 2023-12-18 13:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actividades', '0004_alter_friendship_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='creator_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='friends',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
